# Generated by Django 4.0.4 on 2022-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_remove_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
