# Generated by Django 4.0.4 on 2022-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_event_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
