# Generated by Django 4.0.4 on 2022-04-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_booking_adults_booking_child_bookingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fooditems',
        ),
    ]
