# Generated by Django 4.0.4 on 2022-04-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_remove_booking_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cardno',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='progress',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
